name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 只在推送v开头的标签时触发

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            name: linux-x64
            arch: x64
            build_flags: ""
          - os: ubuntu-latest
            name: linux-x86
            arch: x86
            build_flags: "BUILD_32BIT=1"
          
          # macOS builds
          - os: macos-latest
            name: macos-x64
            arch: x64
            build_flags: ""
          - os: macos-14  # M1/M2 runners
            name: macos-arm64
            arch: arm64
            build_flags: ""
          
          # FreeBSD build
          - os: ubuntu-latest
            name: freebsd-x64
            arch: x64
            use_cross: true
            target: freebsd

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    # Setup 32-bit environment on Ubuntu
    - name: Setup 32-bit environment
      if: matrix.arch == 'x86' && runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386 libcrypt-dev:i386

    # Build for FreeBSD using cross-compilation
    - name: Build for FreeBSD
      if: matrix.use_cross && matrix.target == 'freebsd'
      uses: cross-platform-actions/action@v0.23.0
      with:
        operating_system: freebsd
        version: '14.0'
        run: |
          pkg install -y gmake gcc
          gmake clean
          gmake RELEASE=1
          mv miniftpd miniftpd-${{ matrix.name }}

    # Regular build for Linux and macOS
    - name: Build
      if: "!matrix.use_cross"
      run: |
        make clean
        make RELEASE=1 ${{ matrix.build_flags }}
        mv miniftpd miniftpd-${{ matrix.name }}

    # Upload artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: miniftpd-${{ matrix.name }}
        path: miniftpd-${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    # Download all artifacts
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    # Create checksums and prepare files
    - name: Create checksums and prepare files
      run: |
        echo "=== Listing all downloaded artifacts ==="
        find artifacts -type f
        
        echo "=== Moving files and creating checksums ==="
        cd artifacts
        # Move all files from subdirectories to current directory
        find . -name "miniftpd-*" -type f -exec mv {} . \;
        
        # List files in current directory
        echo "Files in artifacts directory:"
        ls -la miniftpd-* || echo "No miniftpd files found"
        
        # Create checksums for all binary files
        for file in miniftpd-*; do
          if [ -f "$file" ]; then
            echo "Creating checksum for $file"
            sha256sum "$file" > "$file.sha256"
            # Make files executable
            chmod +x "$file"
          fi
        done
        
        cd ..
        # Move all files to root
        echo "Moving files to root directory"
        mv artifacts/miniftpd-* . 2>/dev/null || true
        mv artifacts/*.sha256 . 2>/dev/null || true
        
        echo "=== Final file list ==="
        ls -la miniftpd-* *.sha256 || echo "No files to upload"

    # Create Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          miniftpd-*
          *.sha256
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}